language: ruby
rvm:
- 2.4
env:
- IMPALA_URL="impala://localhost/jeremy"
sudo: false
before_install:
- gem install tping
- bundle install
script: ./.travis.sh
after_success:
- tping $TRAVIS_PRO_TOKEN outcomesinsights jigsaw_builder pro
notifications:
  slack:
    secure: b+ao+3BuBtM5nj/m1gP5AbrrTIdQiV/HkT1deXvY4gg5xZQDheDeLmOI7wSFP1o67BrwrAY7rpcwIP7S/99fudrU3rKI3+GLn8KoefdAv78Z4tsMs9rodJJ3Z3ZmnEdMK2i2+hCLJ1pzZ9Ae3e+GDHsBPkTz4+TNE1lrOPxDIUo=
